### ISSUE TITLE
Alert on wrong login information

### ISSUE THREAD

**Issue by FadiGarana** [bfritscher/grademanager#151]
Actually there is no information if the logs information are incorrect (the login+password combination)

The application should warn the users that something went wrong. However be carefull to not signal any additional information for security purpose (the alert shouldn't tell if it's the login or the password that is incorrect, but simply that something went wrong)

**Comment by AndrePims** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Afficher un message d'erreur au login](https://trello.com/c/7G71YRWf/1-afficher-un-message-derreur-au-login)
