### ISSUE TITLE
Security URL access

### ISSUE THREAD

**Issue by FadiGarana** [bfritscher/grademanager#162]
If the users knows the name of a project he can litterally access it without any issue. 
Indeed it is possible for anyone that knows AMC's URL and a project name to access a project that he does not own.
This is only working when switching account on **the same machine** (because of logout function not properly ending the **token** session) **#103** 

He can eventually put a /options in the URL and mess with the options as well as adding himself as a user.

**Comment by bfritscher** [comment]
Cannot reproduce
